Cb 11 aws comprehend api
Codubee/StockPredictionMW2-4 pull request #17
Opened 2020-12-19 03:24 UTC by Nirvair-Sangha

* **Please check if the PR fulfills these requirements**
- [ ] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)

Adds new feature to allow the user to call the custom api to get the sentiment value.

* **What is the current behavior?What does the code do before you made the new changes?** 

Before the code uses gets to call on other APIs, but now it is able to call the Comprehend Custom API.

* **What is the new behavior?**

The code posts to /checkNews and analyzes for a response and returns a value depending on the response.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)

No

* **Other information**:

2020-12-19 19:06 UTC, Codubee commented
Hey Nick, I think you might have pushed node_modules mistakenly.

2020-12-19 20:17 UTC, DHua5922 requested changes

2020-12-19 20:17 UTC, DHua5922 commented on backend/test/index_test.js
> +        .post('/checkNews')
Indent lines 20-25 by 1 tab so that the code is easier to read.

2020-12-19 20:17 UTC, DHua5922 commented on backend/index.js
> +    .then(function (response) {
Indent lines 22-29 by 1 tab so that the code is easier to read.

2020-12-19 20:17 UTC, DHua5922 commented on backend/index.js
> +    console.log(req.body);
Remove `console.log`. It is not needed in production.

2020-12-19 23:08 UTC, Nirvair-Sangha commented
> Hey Nick, I think you might have pushed node_modules mistakenly.

Is there any way to revert this change, because I ended up not using the code from the body parser commit anyways.

2020-12-21 20:02 UTC, sunnyguan commented
> > Hey Nick, I think you might have pushed node_modules mistakenly.
> 
> Is there any way to revert this change, because I ended up not using the code from the body parser commit anyways.

Should be fixed now, the `node_modules` were in the root directory, so I don't think they could've been used by either the frontend/backend code anyway.

2020-12-21 23:43 UTC, sunnyguan approved these changes
Looks good to me; tests worked both with Mocha as well as Postman.

2020-12-27 20:16 UTC, Codubee approved these changes

2020-12-27 20:17 UTC, merged