cb-28-call-news-api
Codubee/StockPredictionMW2-4 pull request #20
Opened 2020-12-28 22:20 UTC by DHua5922

* **Please check if the PR fulfills these requirements**
- [X] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)

Company News component calls backend news api.

* **What is the current behavior?What does the code do before you made the new changes?** 

Company News component does not call backend news api. Only fake data was shown.

* **What is the new behavior?**

Company News component calls backend news api.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)

No

* **Other information**:

2020-12-29 20:17 UTC, sunnyguan requested changes

2020-12-29 20:17 UTC, sunnyguan commented on frontend/src/components/StockDetails/CompanyNews/CompanyNews.js
> +        getCompanyNews("AAPL")
You can use `this.props.companyName` to get the company name from the props here

2020-12-30 17:37 UTC, Codubee approved these changes
LGTM!

2020-12-30 19:34 UTC, sunnyguan approved these changes

2020-12-30 19:35 UTC, merged