post request to comprehend api
Codubee/StockPredictionMW2-4 pull request #22
Opened 2020-12-30 19:24 UTC by maahasakhia

* **Please check if the PR fulfills these requirements**
- [ ✔] The pull request title contains the ticket number in the title. For example [CB-1]

* **What kind of change does this PR introduce?** (Bug fix, new feature...)
Connect backend and frontend of Comprehend API Call

* **What is the current behavior?What does the code do before you made the new changes?** 
N/A

* **What is the new behavior?**
call the comprehend api from the frontend using hardcoded headlines. Need to add the companyNews headlines as props once that ticket is merged.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR? Run a new command?)

* **Other information**:

2020-12-30 23:43 UTC, DHua5922 requested changes

2020-12-30 23:43 UTC, DHua5922 commented on frontend/src/components/StockDetails/Prediction/Prediction.js
> +            <h1>Prediction is: {this.state.prediction}</h1>
Change to `this.state.prediction.Sentiment`.

2021-01-04 20:07 UTC, DHua5922 approved these changes

2021-01-09 02:13 UTC, Nirvair-Sangha approved these changes
Looks good to me.

2021-02-01 18:39 UTC, merged